version: "3.9"

services:
  django_app:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

volumes:
  static_volume:
  media_volume:
