name: Django CI/CD Pipeline

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run Django tests
    - name: Run Django tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py migrate
        python manage.py test

    # 5️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-shop-app .

    # 6️⃣ Log in to Render Docker registry
    - name: Log in to Render Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.RENDER_USERNAME }}
        password: ${{ secrets.RENDER_PASSWORD }}

    # 7️⃣ Push Docker image to Render
    - name: Push Docker image
      run: |
        docker tag my-shop-app registry.render.com/my-shop:latest
        docker push registry.render.com/my-shop:latest

    # 8️⃣ Trigger Render deploy
    - name: Trigger Render deployment
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/deploy/srv-your-render-service-id
